version: '3.8'
networks:
  default:
    name: mainnet

services:
  api:
    build: api
    volumes:
      - ./api:/backend
    ports:
      - "5000:5000"

  client:
    build: client
    command: ["npm", "start"]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3001:3000'
    depends_on:
      - api

volumes:
  node-modules:

